export default {
  "TrafficLightManager": "Traffic Light Manager",
  "TrafficSignal": "Ampel",
  "ModDefault": "Standard",
  "Vanilla": "Vanilla",
  "SplitPhasing": "Aufgeteilte Phase",
  "CustomPhase": "Custom Phase",
  "ProtectedRightTurns": "Geschützes rechts abbiegen",
  "ProtectedLeftTurns": "Geschützes links abbiegen",
  "Options": "Optionen",
  "ExclusivePedestrianPhase": "Exklusive Fußgängerphase",
  "LaneDirectionTool": "Fahrspurausrichtung (Experimentell)",
  "Close": "Schließen",
  "Open": "Öffnen",
  "Reset": "Zurücksetzen",
  "Save": "Speichern",
  "PleaseSave": "Bitte speichere die Einstellungen, bevor du eine andere Kreuzung bearbeitest.",
  "PleaseSelectJunction": "Bitte wähle eine Kreuzung aus",
  "GiveWayToOncomingVehicles": "Vorfahrt für entgegenkommende Fahrzeuge",
  "CustomPedestrianDurationMultiplier": "Dauer der Fußgängerphase",
  "CustomPedestrianDurationMultiplierSuffix": "x",
  "AllowTurningOnRed": "Erlaube abbiegen bei Rot",
  "CustomPhaseEditor": "Custom Phase Editor",
  "CanaryBuildWarning": "Bitte beachte, dass du ein Canary-Build verwenden, das mit größerer Wahrscheinlichkeit spiel- oder speicherschädigende Bugs enthält und nur zum Testen gedacht ist. Verwenden Sie diesen Build NICHT für den normalen Spielbetrieb.",
  "LdtMigrationNotice": "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  "LdtRetirementNotice": "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT.",
  "CustomPhaseEditor.Add": "Add Phase",
  "CustomPhaseEditor.Back": "Back",
  "CustomPhaseEditor.ManualControl": "Manual Control",
  "CustomPhaseEditor.Options.Title": "Options",
  "CustomPhaseEditor.Options.Tooltip": "_",
  "CustomPhaseEditor.Options.PrioritiseTrack": "Prioritise tram",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "Prioritise bus",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "Prioritise pedestrian",
  "CustomPhaseEditor.Adjustments.Title": "Adjustments",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "Minimum Duration",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "Maximum Duration",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "Target Duration Multiplier",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "Lane Occupied Multiplier",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "Interval Exponent",
  "CustomPhaseEditor.Statistics.Title": "Statistics",
  "CustomPhaseEditor.Statistics.Timer": "Timer",
  "CustomPhaseEditor.Statistics.Priority": "Priority",
  "CustomPhaseEditor.Statistics.LastRun": "Last Run",
  "CustomPhaseEditor.Statistics.CarFlow": "Car Flow",
  "CustomPhaseEditor.Statistics.LanesOccupied": "Lanes Occupied",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "Weighted Waiting",
  "CustomPhaseEditor.PhaseEndRequested": "Phase End Requested",
  "CustomPhaseEditor.EndPhasePrematurely": "End Phase Prematurely"
};
