export default {
  "TrafficLightManager": "Traffic Light Manager",
  "TrafficSignal": "Traffic Signal",
  "ModDefault": "Default",
  "Vanilla": "Vanilla",
  "SplitPhasing": "Split Phasing",
  "CustomPhase": "Custom Phase",
  "ProtectedRightTurns": "Protected Right-Turns",
  "ProtectedLeftTurns": "Protected Left-Turns",
  "Options": "Options",
  "ExclusivePedestrianPhase": "Exclusive Pedestrian Phase",
  "LaneDirectionTool": "Lane Direction Tool (Experimental)",
  "Close": "Close",
  "Open": "Open",
  "Reset": "Reset",
  "Save": "Save",
  "PleaseSave": "Please save changes before selecting another junction.",
  "PleaseSelectJunction": "Please Select a Junction",
  "GiveWayToOncomingVehicles": "Give Way to Oncoming Vehicles",
  "CustomPedestrianDurationMultiplier": "Pedestrian Phase Duration",
  "CustomPedestrianDurationMultiplierSuffix": "x",
  "AllowTurningOnRed": "Allow Turning on Red",
  "CustomPhaseEditor": "Custom Phase Editor",
  "CanaryBuildWarning": "Please note that you are using a canary build, which is more likely to contain game-breaking or save-breaking bugs and is strictly for playtesting only. DO NOT use this build for normal gameplay.",
  "LdtMigrationNotice": "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  "LdtRetirementNotice": "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT.",
  "CustomPhaseEditor.ChooseGroup": "Choose a group to edit",
  "CustomPhaseEditor.AddTrafficLights": "Add Traffic Lights to Group",
  "CustomPhaseEditor.RemoveTrafficLights": "Remove Traffic Lights from Group",
  "CustomPhaseEditor.Add": "Add Phase",
  "CustomPhaseEditor.Back": "Back",
  "CustomPhaseEditor.ManualControl": "Manual Control",
  "CustomPhaseEditor.TrafficLightsMembers": "Traffic Lights Members",
  "CustomPhaseEditor.AddMember": "Add Member",
  "CustomPhaseEditor.RemoveMember": "Remove Member",
  "CustomPhaseEditor.Options.Title": "Options",
  "CustomPhaseEditor.Options.Tooltip": "Adjust Priority",
  "CustomPhaseEditor.Options.PrioritiseTrack": "Prioritise tram",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "Prioritise bus",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "Prioritise pedestrian",
  "CustomPhaseEditor.Adjustments.Title": "Adjustments",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "Minimum Duration",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "Maximum Duration",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "Target Duration Multiplier",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "Lane Occupied Multiplier",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "Interval Exponent",
  "CustomPhaseEditor.Statistics.Title": "Statistics",
  "CustomPhaseEditor.Statistics.Timer": "Timer",
  "CustomPhaseEditor.Statistics.Priority": "Priority",
  "CustomPhaseEditor.Statistics.LastRun": "Last Run",
  "CustomPhaseEditor.Statistics.CarFlow": "Car Flow",
  "CustomPhaseEditor.Statistics.LanesOccupied": "Lanes Occupied",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "Weighted Waiting",
  "CustomPhaseEditor.PhaseEndRequested": "Phase End Requested",
  "CustomPhaseEditor.EndPhasePrematurely": "End Phase Prematurely"
};
