export default {
  TrafficSignal: "Feux de circulations",
  ModDefault: "Par défaut",
  Vanilla: "Vanilla",
  SplitPhasing: "Phase fractionnée",
  CustomPhase: "Custom Phase",
  ProtectedRightTurns: "Virage à droite protégé",
  ProtectedLeftTurns: "Virage à gauche protégé",
  Options: "Options",
  ExclusivePedestrianPhase: "Feux exclusifs piétons",
  LaneDirectionTool: "Outil de direction par voie (expérimental)",
  Close: "Fermer",
  Open: "Ouvrir",
  Reset: "Réinitialiser",
  Save: "Sauvegarder",
  PleaseSave: "Veuillez enregistrer les modifications avant de sélectionner une autre intersection.",
  PleaseSelectJunction: "Veuillez sélectionner une intersection",
  GiveWayToOncomingVehicles: "Céder le passage aux véhicules venant en sens inverse",
  CustomPedestrianDurationMultiplier: "Durée du feu exclusif aux piétons",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Autoriser les virages lorsque le feu est rouge",
  CustomPhaseEditor: "Custom Phase Editor",
  CanaryBuildWarning: "Veuillez noter que vous utilisez une version nouvellement compilée qui n",
  LdtMigrationNotice: "Lane Direction Tool a maintenant été retiré et remplacé par le mod Traffic de krzychu124. Veuillez installer le mod Traffic, et il transférera automatiquement vos paramètres actuels. Cliquez pour plus de détails (Ouvrir dans un navigateur Web).",
  LdtRetirementNotice: "Lane Direction Tool a maintenant été retiré et remplacé par le mod Traffic de krzychu124. Merci d"
};
