export default {
  "TrafficLightManager": "Traffic Light Manager",
  "TrafficSignal": "Feux de circulations",
  "ModDefault": "Par défaut",
  "Vanilla": "Vanilla",
  "SplitPhasing": "Phase fractionnée",
  "CustomPhase": "Custom Phase",
  "ProtectedRightTurns": "Virage à droite protégé",
  "ProtectedLeftTurns": "Virage à gauche protégé",
  "Options": "Options",
  "ExclusivePedestrianPhase": "Feux exclusifs piétons",
  "LaneDirectionTool": "Outil de direction par voie (expérimental)",
  "Close": "Fermer",
  "Open": "Ouvrir",
  "Reset": "Réinitialiser",
  "Save": "Sauvegarder",
  "PleaseSave": "Veuillez enregistrer les modifications avant de sélectionner une autre intersection.",
  "PleaseSelectJunction": "Veuillez sélectionner une intersection",
  "GiveWayToOncomingVehicles": "Céder le passage aux véhicules venant en sens inverse",
  "CustomPedestrianDurationMultiplier": "Durée du feu exclusif aux piétons",
  "CustomPedestrianDurationMultiplierSuffix": "x",
  "AllowTurningOnRed": "Autoriser les virages lorsque le feu est rouge",
  "CustomPhaseEditor": "Custom Phase Editor",
  "CanaryBuildWarning": "Veuillez noter que vous utilisez une version nouvellement compilée qui n",
  "LdtMigrationNotice": "Lane Direction Tool a maintenant été retiré et remplacé par le mod Traffic de krzychu124. Veuillez installer le mod Traffic, et il transférera automatiquement vos paramètres actuels. Cliquez pour plus de détails (Ouvrir dans un navigateur Web).",
  "LdtRetirementNotice": "Lane Direction Tool a maintenant été retiré et remplacé par le mod Traffic de krzychu124. Merci d",
  "CustomPhaseEditor.ChooseGroup": "Choose a group to edit",
  "CustomPhaseEditor.AddTrafficLights": "Add Traffic Lights to Group",
  "CustomPhaseEditor.RemoveTrafficLights": "Remove Traffic Lights from Group",
  "CustomPhaseEditor.Add": "Add Phase",
  "CustomPhaseEditor.Back": "Back",
  "CustomPhaseEditor.ManualControl": "Manual Control",
  "CustomPhaseEditor.TrafficLightsMembers": "Traffic Lights Members",
  "CustomPhaseEditor.AddMember": "Add Member",
  "CustomPhaseEditor.RemoveMember": "Remove Member",
  "CustomPhaseEditor.Options.Title": "Options",
  "CustomPhaseEditor.Options.Tooltip": "_",
  "CustomPhaseEditor.Options.PrioritiseTrack": "Prioritise tram",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "Prioritise bus",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "Prioritise pedestrian",
  "CustomPhaseEditor.Adjustments.Title": "Adjustments",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "Minimum Duration",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "Maximum Duration",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "Target Duration Multiplier",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "Lane Occupied Multiplier",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "Interval Exponent",
  "CustomPhaseEditor.Statistics.Title": "Statistics",
  "CustomPhaseEditor.Statistics.Timer": "Timer",
  "CustomPhaseEditor.Statistics.Priority": "Priority",
  "CustomPhaseEditor.Statistics.LastRun": "Last Run",
  "CustomPhaseEditor.Statistics.CarFlow": "Car Flow",
  "CustomPhaseEditor.Statistics.LanesOccupied": "Lanes Occupied",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "Weighted Waiting",
  "CustomPhaseEditor.PhaseEndRequested": "Phase End Requested",
  "CustomPhaseEditor.EndPhasePrematurely": "End Phase Prematurely"
};
