export default {
  "TrafficLightManager": "Traffic Light Manager",
  "TrafficSignal": "Segnale Di Traffico",
  "ModDefault": "Predefinito",
  "Vanilla": "Base",
  "SplitPhasing": "Separa Fasi",
  "CustomPhase": "Custom Phase",
  "ProtectedRightTurns": "Svolta a destra protetta",
  "ProtectedLeftTurns": "Svolta a sinistra protetta",
  "Options": "Opzioni",
  "ExclusivePedestrianPhase": "Fase Pedonale Esclusiva",
  "LaneDirectionTool": "Strumento Di Direzione Corsia (Sperimentale)",
  "Close": "Chiudi",
  "Open": "Apri",
  "Reset": "Reset",
  "Save": "Salva",
  "PleaseSave": "Si prega di salvare le modifiche prima di selezionare un",
  "PleaseSelectJunction": "Seleziona un incrocio",
  "GiveWayToOncomingVehicles": "Dare precendeza ai veicoli in arrivo",
  "CustomPedestrianDurationMultiplier": "Durata Fase Pedoni",
  "CustomPedestrianDurationMultiplierSuffix": "x",
  "AllowTurningOnRed": "Consenti svolta con rosso",
  "CustomPhaseEditor": "Custom Phase Editor",
  "CanaryBuildWarning": "Si prega di notare che si sta utilizzando una build di canarini, che è più probabile contenere bug di gioco rompente o salva-rottura ed è rigorosamente per il test di gioco. NON usare questa build per il normale gameplay.",
  "LdtMigrationNotice": "Lane Direction Tool è stato ora ritirato e seguito da Traffic mod da krzychu124. Si prega di installare la mod di traffico e trasferirà automaticamente le impostazioni correnti di corsia ad esso. Clicca per maggiori dettagli (Apri in un browser web).",
  "LdtRetirementNotice": "Lo strumento di direzione della corsia è stato ora ritirato ed è riuscito da mod di traffico da krzychu124. Grazie per aver utilizzato LDT.",
  "CustomPhaseEditor.ChooseGroup": "Choose a group to edit",
  "CustomPhaseEditor.AddTrafficLights": "Add Traffic Lights to Group",
  "CustomPhaseEditor.RemoveTrafficLights": "Remove Traffic Lights from Group",
  "CustomPhaseEditor.Add": "Add Phase",
  "CustomPhaseEditor.Back": "Back",
  "CustomPhaseEditor.ManualControl": "Manual Control",
  "CustomPhaseEditor.TrafficLightsMembers": "Traffic Lights Members",
  "CustomPhaseEditor.AddMember": "Add Member",
  "CustomPhaseEditor.RemoveMember": "Remove Member",
  "CustomPhaseEditor.Options.Title": "Options",
  "CustomPhaseEditor.Options.Tooltip": "_",
  "CustomPhaseEditor.Options.PrioritiseTrack": "Prioritise tram",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "Prioritise bus",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "Prioritise pedestrian",
  "CustomPhaseEditor.Adjustments.Title": "Adjustments",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "Minimum Duration",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "Maximum Duration",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "Target Duration Multiplier",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "Lane Occupied Multiplier",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "Interval Exponent",
  "CustomPhaseEditor.Statistics.Title": "Statistics",
  "CustomPhaseEditor.Statistics.Timer": "Timer",
  "CustomPhaseEditor.Statistics.Priority": "Priority",
  "CustomPhaseEditor.Statistics.LastRun": "Last Run",
  "CustomPhaseEditor.Statistics.CarFlow": "Car Flow",
  "CustomPhaseEditor.Statistics.LanesOccupied": "Lanes Occupied",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "Weighted Waiting",
  "CustomPhaseEditor.PhaseEndRequested": "Phase End Requested",
  "CustomPhaseEditor.EndPhasePrematurely": "End Phase Prematurely"
};
