export default {
  TrafficSignal: "Segnale Di Traffico",
  ModDefault: "Predefinito",
  Vanilla: "Base",
  SplitPhasing: "Separa Fasi",
  ProtectedRightTurns: "Svolta a destra protetta",
  ProtectedLeftTurns: "Svolta a sinistra protetta",
  Options: "Opzioni",
  ExclusivePedestrianPhase: "Fase Pedonale Esclusiva",
  LaneDirectionTool: "Strumento Di Direzione Corsia (Sperimentale)",
  Close: "Chiudi",
  Open: "Apri",
  Reset: "Reset",
  Save: "Salva",
  PleaseSave: "Si prega di salvare le modifiche prima di selezionare un'altro incrocio.",
  PleaseSelectJunction: "Seleziona un incrocio",
  GiveWayToOncomingVehicles: "Dare precendeza ai veicoli in arrivo",
  CustomPedestrianDurationMultiplier: "Durata Fase Pedoni",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Consenti svolta con rosso",
  CanaryBuildWarning: "Si prega di notare che si sta utilizzando una build di canarini, che è più probabile contenere bug di gioco rompente o salva-rottura ed è rigorosamente per il test di gioco. NON usare questa build per il normale gameplay.",
  LdtMigrationNotice: "Lane Direction Tool è stato ora ritirato e seguito da Traffic mod da krzychu124. Si prega di installare la mod di traffico e trasferirà automaticamente le impostazioni correnti di corsia ad esso. Clicca per maggiori dettagli (Apri in un browser web).",
  LdtRetirementNotice: "Lo strumento di direzione della corsia è stato ora ritirato ed è riuscito da mod di traffico da krzychu124. Grazie per aver utilizzato LDT."
};