export default {
  "TrafficLightManager": "Traffic Light Manager",
  "TrafficSignal": "信号",
  "ModDefault": "デフォルト",
  "Vanilla": "バニラ",
  "SplitPhasing": "分割式",
  "CustomPhase": "Custom Phase",
  "ProtectedRightTurns": "右折信号",
  "ProtectedLeftTurns": "左折信号",
  "Options": "オプション",
  "ExclusivePedestrianPhase": "歩行者専用フェーズ",
  "LaneDirectionTool": "車線指示ツール（試験的）",
  "Close": "閉じる",
  "Open": "闢く",
  "Reset": "リセット",
  "Save": "保存",
  "PleaseSave": "他の交差点を選択する前に、変更を保存して下さい",
  "PleaseSelectJunction": "交差点を選択して下さい",
  "GiveWayToOncomingVehicles": "対向車に道を譲る",
  "CustomPedestrianDurationMultiplier": "歩行者通行時間",
  "CustomPedestrianDurationMultiplierSuffix": "倍",
  "AllowTurningOnRed": "赤信号を許容する",
  "CustomPhaseEditor": "Custom Phase Editor",
  "CanaryBuildWarning": "Canary buildが実行されていることに注意してください。canary buildは正式版ではないため、ゲームを壊すバグやセーブデータを破壊するバグが含まれている可能性が高いテスト版です。このバージョンは通常のゲームプレイには使用しないでください。",
  "LdtMigrationNotice": "車線方向ツールは廃止され、krzychu124氏のTraffic modに引き継がれました。Traffic modをインストールすると、現在の車線設定が自動的に移行されます。詳しくはこちらをクリックしてください。（ウェブブラウザで開きます）",
  "LdtRetirementNotice": "車線方向ツールは廃止され、krzychu124氏のTraffic modに引き継がれました。これまで当機能をご利用いただきありがとうございました。",
  "CustomPhaseEditor.Add": "Add Phase",
  "CustomPhaseEditor.Back": "Back",
  "CustomPhaseEditor.ManualControl": "Manual Control",
  "CustomPhaseEditor.Options.Title": "Options",
  "CustomPhaseEditor.Options.Tooltip": "_",
  "CustomPhaseEditor.Options.PrioritiseTrack": "Prioritise tram",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "Prioritise bus",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "Prioritise pedestrian",
  "CustomPhaseEditor.Adjustments.Title": "Adjustments",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "Minimum Duration",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "Maximum Duration",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "Target Duration Multiplier",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "Lane Occupied Multiplier",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "Interval Exponent",
  "CustomPhaseEditor.Statistics.Title": "Statistics",
  "CustomPhaseEditor.Statistics.Timer": "Timer",
  "CustomPhaseEditor.Statistics.Priority": "Priority",
  "CustomPhaseEditor.Statistics.LastRun": "Last Run",
  "CustomPhaseEditor.Statistics.CarFlow": "Car Flow",
  "CustomPhaseEditor.Statistics.LanesOccupied": "Lanes Occupied",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "Weighted Waiting",
  "CustomPhaseEditor.PhaseEndRequested": "Phase End Requested",
  "CustomPhaseEditor.EndPhasePrematurely": "End Phase Prematurely"
};
