export default {
  "TrafficLightManager": "Traffic Light Manager",
  "TrafficSignal": "교통 신호",
  "ModDefault": "모드 기본 값",
  "Vanilla": "바닐라 값",
  "SplitPhasing": "분할 신호",
  "CustomPhase": "Custom Phase",
  "ProtectedRightTurns": "우회전 단계 보호",
  "ProtectedLeftTurns": "좌회전 단계 보호",
  "Options": "추가 기능",
  "ExclusivePedestrianPhase": "동시 보행 신호",
  "LaneDirectionTool": "차로 방향 지정 도구 (실험기능)",
  "Close": "닫기",
  "Open": "열기",
  "Reset": "초기화",
  "Save": "저장",
  "PleaseSave": "반드시 저장 후 다른 교차로를 선택하십시오",
  "PleaseSelectJunction": "교차로를 선택 하십시오",
  "GiveWayToOncomingVehicles": "회전 차량 우선 양보 (바닐라 신호만 해당)",
  "CustomPedestrianDurationMultiplier": "보행 신호 지속 시간",
  "CustomPedestrianDurationMultiplierSuffix": "x",
  "AllowTurningOnRed": "적신호시 우회전 (우측통행 기준) 허용",
  "CustomPhaseEditor": "Custom Phase Editor",
  "CanaryBuildWarning": "canary build 사용 전 유의사항, 해당 빌드는 테스트 전용이므로 저장 파일이 망가지거나 버그가 발생 할 수 있습니다. 일반적인 경우에는 사용하지 마십시오.",
  "LdtMigrationNotice": "차선 방향 도구는 이제 폐기되었으며 krzychu124의 Traffic 모드로 계승되었습니다. Traffic 모드를 설치하면 현재 차선 설정이 자동으로 전송됩니다. 자세한 내용을 보려면 클릭하세요(웹 브라우저에서 열기).",
  "LdtRetirementNotice": "차로 방향 도구는 이제 폐기되었으며 krzychu124의 Traffic 모드로 계승되었습니다. LDT를 이용해 주셔서 감사합니다.",
  "CustomPhaseEditor.ChooseGroup": "Choose a group to edit",
  "CustomPhaseEditor.AddTrafficLights": "Add Traffic Lights to Group",
  "CustomPhaseEditor.RemoveTrafficLights": "Remove Traffic Lights from Group",
  "CustomPhaseEditor.Add": "Add Phase",
  "CustomPhaseEditor.Back": "Back",
  "CustomPhaseEditor.ManualControl": "Manual Control",
  "CustomPhaseEditor.TrafficLightsMembers": "Traffic Lights Members",
  "CustomPhaseEditor.AddMember": "Add Member",
  "CustomPhaseEditor.RemoveMember": "Remove Member",
  "CustomPhaseEditor.Options.Title": "Options",
  "CustomPhaseEditor.Options.Tooltip": "_",
  "CustomPhaseEditor.Options.PrioritiseTrack": "Prioritise tram",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "Prioritise bus",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "Prioritise pedestrian",
  "CustomPhaseEditor.Adjustments.Title": "Adjustments",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "Minimum Duration",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "Maximum Duration",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "Target Duration Multiplier",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "Lane Occupied Multiplier",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "Interval Exponent",
  "CustomPhaseEditor.Statistics.Title": "Statistics",
  "CustomPhaseEditor.Statistics.Timer": "Timer",
  "CustomPhaseEditor.Statistics.Priority": "Priority",
  "CustomPhaseEditor.Statistics.LastRun": "Last Run",
  "CustomPhaseEditor.Statistics.CarFlow": "Car Flow",
  "CustomPhaseEditor.Statistics.LanesOccupied": "Lanes Occupied",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "Weighted Waiting",
  "CustomPhaseEditor.PhaseEndRequested": "Phase End Requested",
  "CustomPhaseEditor.EndPhasePrematurely": "End Phase Prematurely"
};
