export default {
  "TrafficLightManager": "Traffic Light Manager",
  "TrafficSignal": "Verkeerslicht",
  "ModDefault": "Default",
  "Vanilla": "Standaard",
  "SplitPhasing": "Gescheiden fasering",
  "CustomPhase": "Custom Phase",
  "ProtectedRightTurns": "Beschermde bochten naar rechts",
  "ProtectedLeftTurns": "Beschermde bochten naar links",
  "Options": "Opties",
  "ExclusivePedestrianPhase": "Exclusieve voetgangers fase",
  "LaneDirectionTool": "Voorsorteren (Experimenteel)",
  "Close": "Sluiten",
  "Open": "Openen",
  "Reset": "Herstellen",
  "Save": "Opslaan",
  "PleaseSave": "Sla de wijzigingen op voordat u een andere kruising selecteert.",
  "PleaseSelectJunction": "Selecteer een kruising",
  "GiveWayToOncomingVehicles": "Geef voorrang aan naderende voertuigen",
  "CustomPedestrianDurationMultiplier": "Duur van de voetgangersfase",
  "CustomPedestrianDurationMultiplierSuffix": "x",
  "AllowTurningOnRed": "Toestaan ​​om rechtsaf te slaan bij rood licht",
  "CustomPhaseEditor": "Custom Phase Editor",
  "CanaryBuildWarning": "Houd er rekening mee dat je een testversie gebruikt, die waarschijnlijk ernstige fouten kan bevatten die het spel of je voortgang kunnen verstoren. Gebruik deze versie NIET voor normale spellen.",
  "LdtMigrationNotice": "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  "LdtRetirementNotice": "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT.",
  "CustomPhaseEditor.ChooseGroup": "Choose a group to edit",
  "CustomPhaseEditor.AddTrafficLights": "Add Traffic Lights to Group",
  "CustomPhaseEditor.RemoveTrafficLights": "Remove Traffic Lights from Group",
  "CustomPhaseEditor.Add": "Add Phase",
  "CustomPhaseEditor.Back": "Back",
  "CustomPhaseEditor.ManualControl": "Manual Control",
  "CustomPhaseEditor.TrafficLightsMembers": "Traffic Lights Members",
  "CustomPhaseEditor.AddMember": "Add Member",
  "CustomPhaseEditor.RemoveMember": "Remove Member",
  "CustomPhaseEditor.Options.Title": "Options",
  "CustomPhaseEditor.Options.Tooltip": "_",
  "CustomPhaseEditor.Options.PrioritiseTrack": "Prioritise tram",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "Prioritise bus",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "Prioritise pedestrian",
  "CustomPhaseEditor.Adjustments.Title": "Adjustments",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "Minimum Duration",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "Maximum Duration",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "Target Duration Multiplier",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "Lane Occupied Multiplier",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "Interval Exponent",
  "CustomPhaseEditor.Statistics.Title": "Statistics",
  "CustomPhaseEditor.Statistics.Timer": "Timer",
  "CustomPhaseEditor.Statistics.Priority": "Priority",
  "CustomPhaseEditor.Statistics.LastRun": "Last Run",
  "CustomPhaseEditor.Statistics.CarFlow": "Car Flow",
  "CustomPhaseEditor.Statistics.LanesOccupied": "Lanes Occupied",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "Weighted Waiting",
  "CustomPhaseEditor.PhaseEndRequested": "Phase End Requested",
  "CustomPhaseEditor.EndPhasePrematurely": "End Phase Prematurely"
};
