export default {
  TrafficSignal: "Verkeerslicht",
  ModDefault: "Default",
  Vanilla: "Standaard",
  SplitPhasing: "Gescheiden fasering",
  ProtectedRightTurns: "Beschermde bochten naar rechts",
  ProtectedLeftTurns: "Beschermde bochten naar links",
  Options: "Opties",
  ExclusivePedestrianPhase: "Exclusieve voetgangers fase",
  LaneDirectionTool: "Voorsorteren (Experimenteel)",
  Close: "Sluiten",
  Open: "Openen",
  Reset: "Herstellen",
  Save: "Opslaan",
  PleaseSave: "Sla de wijzigingen op voordat u een andere kruising selecteert.",
  PleaseSelectJunction: "Selecteer een kruising",
  GiveWayToOncomingVehicles: "Geef voorrang aan naderende voertuigen",
  CustomPedestrianDurationMultiplier: "Duur van de voetgangersfase",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Toestaan ​​om rechtsaf te slaan bij rood licht",
  CanaryBuildWarning: "Houd er rekening mee dat je een testversie gebruikt, die waarschijnlijk ernstige fouten kan bevatten die het spel of je voortgang kunnen verstoren. Gebruik deze versie NIET voor normale spellen.",
  LdtMigrationNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  LdtRetirementNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT."
};