export default {
  TrafficSignal: "Sygnalizacja świetlna",
  ModDefault: "Domyślna",
  Vanilla: "Z gry",
  SplitPhasing: "Bezkolizyjna",
  ProtectedRightTurns: "Dedykowany prawoskręt",
  ProtectedLeftTurns: "Dedykowany lewoskręt",
  Options: "Opcje",
  ExclusivePedestrianPhase: "Dedykowana faza dla pieszych",
  LaneDirectionTool: "Narzędzie zmiany strzałek pasów (Eksperymentalne)",
  Close: "Zamknij",
  Open: "Otwórz",
  Reset: "Reset",
  Save: "Zapisz",
  PleaseSave: "Proszę zapisać zmiany przed wybraniem innego skrzyżowania.",
  PleaseSelectJunction: "Wybierz skrzyżowanie",
  GiveWayToOncomingVehicles: "Ustąp pierwszeństwa pojazdom z naprzeciwka",
  CustomPedestrianDurationMultiplier: "Czas trwania fazy dla pieszych",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Pozwalaj na skręcanie na czerwonym",
  CanaryBuildWarning: "Pamiętaj, że używasz wersji canary, która może zawiera błędy psujące grę lub powodujące uszkodzenie zapisu i jest przeznaczona wyłącznie do testowania gry. NIE używaj tej wersji do normalnej rozgrywki.",
  LdtMigrationNotice: "Narzędzie zmiany strzałek pasów zostało wycofane i zastąpione modem Traffic od krzychu124. Zainstaluj moda Traffic i on automatycznie przeniesie ustawienia pasów. Kliknij tutaj, aby przeczytać. (Otwórz w przeglądarce).",
  LdtRetirementNotice: "Narzędzie zmiany strzałek pasów zostało wycofane i zastąpione modem Traffic od krzychu124. Dziękuje za skorzystanie z narzędzia zmiany strzałek pasów."
};