export default {
  "TrafficLightManager": "Traffic Light Manager",
  "TrafficSignal": "Sinal de Trânsito",
  "ModDefault": "Default",
  "Vanilla": "Sem modificação",
  "SplitPhasing": "Divisão de Fases",
  "CustomPhase": "Custom Phase",
  "ProtectedRightTurns": "Conversões à Direita Protegidas",
  "ProtectedLeftTurns": "Conversões à Esquerda Protegidas",
  "Options": "Opções",
  "ExclusivePedestrianPhase": "Fase Exclusiva para Pedestres",
  "LaneDirectionTool": "Ferramenta de Direção de Pista (Experimental)",
  "Close": "Fechar",
  "Open": "Abrir",
  "Reset": "Redefinir",
  "Save": "Salvar",
  "PleaseSave": "Por favor, salve as alterações antes de selecionar outra cruzamento.",
  "PleaseSelectJunction": "Por favor, selecione uma cruzamento",
  "GiveWayToOncomingVehicles": "Prioridade aos veículos se aproximando",
  "CustomPedestrianDurationMultiplier": "Duração da fase dos Pedestres",
  "CustomPedestrianDurationMultiplierSuffix": "x",
  "AllowTurningOnRed": "Permitir Conversão no Vermelho",
  "CustomPhaseEditor": "Custom Phase Editor",
  "CanaryBuildWarning": "Please note that you are using a canary build, which is more likely to contain game-breaking or save-breaking bugs and is strictly for playtesting only. DO NOT use this build for normal gameplay.",
  "LdtMigrationNotice": "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  "LdtRetirementNotice": "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT.",
  "CustomPhaseEditor.ChooseGroup": "Choose a group to edit",
  "CustomPhaseEditor.AddTrafficLights": "Add Traffic Lights to Group",
  "CustomPhaseEditor.RemoveTrafficLights": "Remove Traffic Lights from Group",
  "CustomPhaseEditor.Add": "Add Phase",
  "CustomPhaseEditor.Back": "Back",
  "CustomPhaseEditor.ManualControl": "Manual Control",
  "CustomPhaseEditor.TrafficLightsMembers": "Traffic Lights Members",
  "CustomPhaseEditor.AddMember": "Add Member",
  "CustomPhaseEditor.RemoveMember": "Remove Member",
  "CustomPhaseEditor.Options.Title": "Options",
  "CustomPhaseEditor.Options.Tooltip": "_",
  "CustomPhaseEditor.Options.PrioritiseTrack": "Prioritise tram",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "Prioritise bus",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "Prioritise pedestrian",
  "CustomPhaseEditor.Adjustments.Title": "Adjustments",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "Minimum Duration",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "Maximum Duration",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "Target Duration Multiplier",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "Lane Occupied Multiplier",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "Interval Exponent",
  "CustomPhaseEditor.Statistics.Title": "Statistics",
  "CustomPhaseEditor.Statistics.Timer": "Timer",
  "CustomPhaseEditor.Statistics.Priority": "Priority",
  "CustomPhaseEditor.Statistics.LastRun": "Last Run",
  "CustomPhaseEditor.Statistics.CarFlow": "Car Flow",
  "CustomPhaseEditor.Statistics.LanesOccupied": "Lanes Occupied",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "Weighted Waiting",
  "CustomPhaseEditor.PhaseEndRequested": "Phase End Requested",
  "CustomPhaseEditor.EndPhasePrematurely": "End Phase Prematurely"
};
