export default {
  TrafficSignal: "Светофор",
  ModDefault: "По умолчанию (мод)",
  Vanilla: "Внутриигровой",
  SplitPhasing: "Очередь",
  ProtectedRightTurns: "Защищенные правые повороты",
  ProtectedLeftTurns: "Защищенные левые повороты",
  Options: "Настройки",
  ExclusivePedestrianPhase: "Отдельная фаза для пешеходов",
  LaneDirectionTool: "Настройка направления полос (экспериментально)",
  Close: "Закрыть",
  Open: "Открыть",
  Reset: "Сбросить",
  Save: "Сохранить",
  PleaseSave: "Пожалуйста, сохраните изменения, прежде чем выбирать другой перекресток",
  PleaseSelectJunction: "Пожалуйста, выберите перекресток",
  GiveWayToOncomingVehicles: "Уступить дорогу встречному транспорту",
  CustomPedestrianDurationMultiplier: "Продолжительность фазы для пешеходов",
  CustomPedestrianDurationMultiplierSuffix: "⨯",
  AllowTurningOnRed: "Разрешить поворот на красный свет",
  CanaryBuildWarning: "Обратите внимание, что вы используете тестовую сборку, которая может содержать ошибки, нарушающие игровой процесс или может повредить сохранение, и предназначена исключительно для тестирования. НЕ используйте эту сборку для обычной игры.",
  LdtMigrationNotice: "Инструмент \"Настройка направления полос\" был отключен и заменен модификацией \"Traffic mod\" от krzychu124. Пожалуйста, установите модификацию \"Traffic mod\" и она автоматически перенесет ваши текущие настройки полос. Нажмите для получения дополнительных деталей (открыть в веб-браузере).",
  LdtRetirementNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT."
};