export default {
  "TrafficLightManager": "Traffic Light Manager",
  "TrafficSignal": "Светофор",
  "ModDefault": "По умолчанию (мод)",
  "Vanilla": "Внутриигровой",
  "SplitPhasing": "Очередь",
  "CustomPhase": "Custom Phase",
  "ProtectedRightTurns": "Защищенные правые повороты",
  "ProtectedLeftTurns": "Защищенные левые повороты",
  "Options": "Настройки",
  "ExclusivePedestrianPhase": "Отдельная фаза для пешеходов",
  "LaneDirectionTool": "Настройка направления полос (экспериментально)",
  "Close": "Закрыть",
  "Open": "Открыть",
  "Reset": "Сбросить",
  "Save": "Сохранить",
  "PleaseSave": "Пожалуйста, сохраните изменения, прежде чем выбирать другой перекресток",
  "PleaseSelectJunction": "Пожалуйста, выберите перекресток",
  "GiveWayToOncomingVehicles": "Уступить дорогу встречному транспорту",
  "CustomPedestrianDurationMultiplier": "Продолжительность фазы для пешеходов",
  "CustomPedestrianDurationMultiplierSuffix": "⨯",
  "AllowTurningOnRed": "Разрешить поворот на красный свет",
  "CustomPhaseEditor": "Custom Phase Editor",
  "CanaryBuildWarning": "Обратите внимание, что вы используете тестовую сборку, которая может содержать ошибки, нарушающие игровой процесс или может повредить сохранение, и предназначена исключительно для тестирования. НЕ используйте эту сборку для обычной игры.",
  "LdtMigrationNotice": "Инструмент \"Настройка направления полос\" был отключен и заменен модификацией \"Traffic mod\" от krzychu124. Пожалуйста, установите модификацию \"Traffic mod\" и она автоматически перенесет ваши текущие настройки полос. Нажмите для получения дополнительных деталей (открыть в веб-браузере).",
  "LdtRetirementNotice": "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT.",
  "CustomPhaseEditor.ChooseGroup": "Choose a group to edit",
  "CustomPhaseEditor.AddTrafficLights": "Add Traffic Lights to Group",
  "CustomPhaseEditor.RemoveTrafficLights": "Remove Traffic Lights from Group",
  "CustomPhaseEditor.Add": "Add Phase",
  "CustomPhaseEditor.Back": "Back",
  "CustomPhaseEditor.ManualControl": "Manual Control",
  "CustomPhaseEditor.TrafficLightsMembers": "Traffic Lights Members",
  "CustomPhaseEditor.AddMember": "Add Member",
  "CustomPhaseEditor.RemoveMember": "Remove Member",
  "CustomPhaseEditor.Options.Title": "Options",
  "CustomPhaseEditor.Options.Tooltip": "_",
  "CustomPhaseEditor.Options.PrioritiseTrack": "Prioritise tram",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "Prioritise bus",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "Prioritise pedestrian",
  "CustomPhaseEditor.Adjustments.Title": "Adjustments",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "Minimum Duration",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "Maximum Duration",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "Target Duration Multiplier",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "Lane Occupied Multiplier",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "Interval Exponent",
  "CustomPhaseEditor.Statistics.Title": "Statistics",
  "CustomPhaseEditor.Statistics.Timer": "Timer",
  "CustomPhaseEditor.Statistics.Priority": "Priority",
  "CustomPhaseEditor.Statistics.LastRun": "Last Run",
  "CustomPhaseEditor.Statistics.CarFlow": "Car Flow",
  "CustomPhaseEditor.Statistics.LanesOccupied": "Lanes Occupied",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "Weighted Waiting",
  "CustomPhaseEditor.PhaseEndRequested": "Phase End Requested",
  "CustomPhaseEditor.EndPhasePrematurely": "End Phase Prematurely"
};
