export default {
  TrafficSignal: "信号灯",
  ModDefault: "默认",
  Vanilla: "原版",
  SplitPhasing: "分隔式信号灯",
  ProtectedRightTurns: "专属右转",
  ProtectedLeftTurns: "专属左转",
  Options: "选项",
  ExclusivePedestrianPhase: "行人专用通行时段",
  LaneDirectionTool: "行车线方向设定（实验中）",
  Close: "关闭",
  Open: "开启",
  Reset: "重置",
  Save: "保存",
  PleaseSave: "在选择另一路口前，请保存当前设定。",
  PleaseSelectJunction: "请选择路口",
  GiveWayToOncomingVehicles: "让路给迎面驶来的车辆",
  CustomPedestrianDurationMultiplier: "行人通行时段长短",
  CustomPedestrianDurationMultiplierSuffix: "倍",
  AllowTurningOnRed: "容许于红灯时转弯",
  CanaryBuildWarning: "请注意，你正在使用Canary版。此版本仅供测试之用，很可能会导致游戏崩溃或存档损坏。敬请避免使用此版本进行游戏。",
  LdtMigrationNotice: "行车线方向设定工具现已退役，并由 krzychu124 的 Traffic Mod 接替。请安装 Traffic Mod，它将自动转移你的车道设置。点击查看更多详情（在网页浏览器中打开）",
  LdtRetirementNotice: "行车线方向设定工具现已退役，并由 krzychu124 的 Traffic Mod 接替。感谢你使用本工具。"
};