export default {
  "TrafficLightManager": "信号灯管理器",
  "TrafficSignal": "交通號誌",
  "ModDefault": "預設",
  "Vanilla": "原版",
  "SplitPhasing": "輪放多時相號誌",
  "CustomPhase": "自定义",
  "ProtectedRightTurns": "右轉保護時相",
  "ProtectedLeftTurns": "左轉保護時相",
  "Options": "選項",
  "ExclusivePedestrianPhase": "行人專用時相",
  "LaneDirectionTool": "車道遵行方向設定 (實驗中)",
  "Close": "關閉",
  "Open": "開啟",
  "Reset": "重設",
  "Save": "儲存",
  "PleaseSave": "在選擇另一路口前，請先儲存設定。",
  "PleaseSelectJunction": "請選擇路口",
  "GiveWayToOncomingVehicles": "讓路給迎面駛來的車輛",
  "CustomPedestrianDurationMultiplier": "行人時相長短",
  "CustomPedestrianDurationMultiplierSuffix": "倍",
  "AllowTurningOnRed": "容許於紅燈時轉彎",
  "CustomPhaseEditor": "相位编辑器",
  "CanaryBuildWarning": "請注意，你正在使用Canary版。此版本僅供測試之用，很可能會導致遊戲崩潰或存檔損壞。敬請避免使用此版本進行遊戲。",
  "LdtMigrationNotice": "車道遵行方向現已退役，並由 krzychu124 的 Traffic Mod 接替。請安裝 Traffic Mod，它將自動轉移你的車道設置。點擊查看更多詳情（在網頁瀏覽器中開啟）",
  "LdtRetirementNotice": "車道遵行方向設定工具現已退役，並由 krzychu124 的 Traffic Mod 接替。感謝你使用本工具。",
  "CustomPhaseEditor.Add": "添加相位",
  "CustomPhaseEditor.Back": "返回",
  "CustomPhaseEditor.ManualControl": "手动控制",
  "CustomPhaseEditor.Options.Title": "选项",
  "CustomPhaseEditor.Options.Tooltip": "_",
  "CustomPhaseEditor.Options.PrioritiseTrack": "有轨电车优先",
  "CustomPhaseEditor.Options.PrioritisePublicCar": "公交车优先",
  "CustomPhaseEditor.Options.PrioritisePedestrian": "行人优先",
  "CustomPhaseEditor.Adjustments.Title": "调整",
  "CustomPhaseEditor.Adjustments.MinimumDuration": "最小持续时间",
  "CustomPhaseEditor.Adjustments.MaximumDuration": "最大持续时间",
  "CustomPhaseEditor.Adjustments.TargetDurationMultiplier": "目标持续时间倍数",
  "CustomPhaseEditor.Adjustments.LaneOccupiedMultiplier": "车道占用倍数",
  "CustomPhaseEditor.Adjustments.IntervalExponent": "间隔指数",
  "CustomPhaseEditor.Statistics.Title": "统计信息",
  "CustomPhaseEditor.Statistics.Timer": "计时器",
  "CustomPhaseEditor.Statistics.Priority": "优先级",
  "CustomPhaseEditor.Statistics.LastRun": "上次运行",
  "CustomPhaseEditor.Statistics.CarFlow": "车辆流量",
  "CustomPhaseEditor.Statistics.LanesOccupied": "车道占用",
  "CustomPhaseEditor.Statistics.WeightedWaiting": "加权等待时间",
  "CustomPhaseEditor.PhaseEndRequested": "相位结束请求",
  "CustomPhaseEditor.EndPhasePrematurely": "相位提前结束"
};
