export default {
  TrafficSignal: "Traffic Signal",
  ModDefault: "Default",
  Vanilla: "Vanilla",
  SplitPhasing: "Split Phasing",
  ProtectedRightTurns: "Protected Right-Turns",
  ProtectedLeftTurns: "Protected Left-Turns",
  Options: "Options",
  ExclusivePedestrianPhase: "Exclusive Pedestrian Phase",
  LaneDirectionTool: "Lane Direction Tool (Experimental)",
  Close: "Close",
  Open: "Open",
  Reset: "Reset",
  Save: "Save",
  PleaseSave: "Please save changes before selecting another junction.",
  PleaseSelectJunction: "Please Select a Junction",
  GiveWayToOncomingVehicles: "Give Way to Oncoming Vehicles",
  CustomPedestrianDurationMultiplier: "Pedestrian Phase Duration",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Allow Turning on Red",
  CanaryBuildWarning: "Please note that you are using a canary build, which is more likely to contain game-breaking or save-breaking bugs and is strictly for playtesting only. DO NOT use this build for normal gameplay.",
  LdtMigrationNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  LdtRetirementNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT."
};