export default {
  TrafficSignal: "Señal de tráfico",
  ModDefault: "Por defecto",
  Vanilla: "Vainilla",
  SplitPhasing: "Fase de división",
  ProtectedRightTurns: "Giros derechos protegidos",
  ProtectedLeftTurns: "Giros izquierdos protegidos",
  Options: "Opciones",
  ExclusivePedestrianPhase: "Fase exclusiva para peatones",
  LaneDirectionTool: "Herramienta de dirección de carriles (Experimental)",
  Close: "Cerrar",
  Open: "Abrir",
  Reset: "Restablecer",
  Save: "Guardar",
  PleaseSave: "Por favor guardar los cambios antes de seleccionar otra intersección.",
  PleaseSelectJunction: "Por favor seleccionar una intersección",
  GiveWayToOncomingVehicles: "Ceder el paso a los vehículos entrantes",
  CustomPedestrianDurationMultiplier: "Duración de la fase de peatones",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Permitir giros en rojo",
  CanaryBuildWarning: "Tenga en cuenta que está usando una compilación canaria, que es más probable que contenga errores de ruptura de juegos o de guardado y es estrictamente solo para pruebas de jugabilidad. NO use esta versión para el juego normal.",
  LdtMigrationNotice: "La herramienta de dirección de carriles se ha retirado y ha sido sucedida por el mod Traffic de Krzychu124. Por favor, instala el modo Traffic, y automáticamente se transferirá la configuración de carriles actual. Haga clic para más detalles (Abrir en un navegador web).",
  LdtRetirementNotice: "La herramienta de dirección de carriles se ha retirado y ha sido sucedida por el mod Traffic de Krzychu124. Gracias por utilizar la herramienta de dirección de carriles."
};