export default {
  TrafficSignal: "信号",
  ModDefault: "デフォルト",
  Vanilla: "バニラ",
  SplitPhasing: "分割式",
  ProtectedRightTurns: "右折信号",
  ProtectedLeftTurns: "左折信号",
  Options: "オプション",
  ExclusivePedestrianPhase: "歩行者専用フェーズ",
  LaneDirectionTool: "車線指示ツール（試験的）",
  Close: "閉じる",
  Open: "闢く",
  Reset: "リセット",
  Save: "保存",
  PleaseSave: "他の交差点を選択する前に、変更を保存して下さい",
  PleaseSelectJunction: "交差点を選択して下さい",
  GiveWayToOncomingVehicles: "対向車に道を譲る",
  CustomPedestrianDurationMultiplier: "歩行者通行時間",
  CustomPedestrianDurationMultiplierSuffix: "倍",
  AllowTurningOnRed: "赤信号を許容する",
  CanaryBuildWarning: "Canary buildが実行されていることに注意してください。canary buildは正式版ではないため、ゲームを壊すバグやセーブデータを破壊するバグが含まれている可能性が高いテスト版です。このバージョンは通常のゲームプレイには使用しないでください。",
  LdtMigrationNotice: "車線方向ツールは廃止され、krzychu124氏のTraffic modに引き継がれました。Traffic modをインストールすると、現在の車線設定が自動的に移行されます。詳しくはこちらをクリックしてください。（ウェブブラウザで開きます）",
  LdtRetirementNotice: "車線方向ツールは廃止され、krzychu124氏のTraffic modに引き継がれました。これまで当機能をご利用いただきありがとうございました。"
};