export default {
  TrafficSignal: "Sinal de Trânsito",
  ModDefault: "Default",
  Vanilla: "Sem modificação",
  SplitPhasing: "Divisão de Fases",
  ProtectedRightTurns: "Conversões à Direita Protegidas",
  ProtectedLeftTurns: "Conversões à Esquerda Protegidas",
  Options: "Opções",
  ExclusivePedestrianPhase: "Fase Exclusiva para Pedestres",
  LaneDirectionTool: "Ferramenta de Direção de Pista (Experimental)",
  Close: "Fechar",
  Open: "Abrir",
  Reset: "Redefinir",
  Save: "Salvar",
  PleaseSave: "Por favor, salve as alterações antes de selecionar outra cruzamento.",
  PleaseSelectJunction: "Por favor, selecione uma cruzamento",
  GiveWayToOncomingVehicles: "Prioridade aos veículos se aproximando",
  CustomPedestrianDurationMultiplier: "Duração da fase dos Pedestres",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Permitir Conversão no Vermelho",
  CanaryBuildWarning: "Please note that you are using a canary build, which is more likely to contain game-breaking or save-breaking bugs and is strictly for playtesting only. DO NOT use this build for normal gameplay.",
  LdtMigrationNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  LdtRetirementNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT."
};